!function(Sa,m,ra,N,Ta,ea,h,Ua,Va,sa,fa,ta,ua,Wa,ga,va,Xa,O,wa,Ya,Za,pb,P,xa,$a,q,qb,ya,Q,za,Aa,ha,ab,rb,bb,cb,R,db,Ba,Ca,eb,w,r,ia,J,A,S,T,x,Da){function s(a,c,b){if(d[ua])a[ua](c,b,!1);else a[Wa](za+c,b)}function U(a){a=d[bb][eb][Ba]().match(Ua(a+"[/ ](\\d+)","i"));return h(a&&a[1],10)}function ja(a,c,b){a=a[Aa](c!=ea?c:ta+":"+ga,b!=ea?b:"_"+ga);t(a,q);t(a,Ya);return a}function ka(a){a=a||window.event||{};if(1<a.which||0<a.button)return!0;for(a=a.target||a.srcElement;a;){if(a["91c4"])return!0;a=
a.parentNode}return!1}function F(a,c){a=h(a,10);isNaN(a)&&(a=h(V&&V.getItem(c)||_GPL.gc(c,10),10)||0);return a}function K(a,c,b){a=h(a,10)||0;c=h(c,10)||0;b=h(b,10)||0;var g=n(),Ea=e&&(new m(1E3*a)).getDate()!=(new m(1E3*g)).getDate();Ea&&(c=e=0);a=!B||g-a>=j&&c<B;b=g-b>=C;return!G&&Ea||a&&b}function t(a,c){try{a[c]()}catch(b){}}function W(a){if(!ka(a)){if(a=X)if(a=la()){a=wa+"Height";var c=wa+"Width";a=N(768,h(d.innerHeight||Fa[a]||Y[a],10)||0,10);c=N(1024,h(d.innerWidth||Fa[c]||Y[c],10)||0);a="left="+
(d[R+"Left"]||d[R+"X"])+",top="+(d[R+"Top"]||d[R+"Y"])+",width="+c+",height="+a+",status=true,toolbar=false,menubar=true,resizable=true,location=false,directories=no,scrollbars=true,copyhistory=no";a=d[Aa](_GPL.proto+_GPL.baseCDN+"/p.html?u="+encodeURIComponent(Ga),"ld893_"+(L?"_"+encodeURIComponent(L)+"_":"")+"_"+n(),a)}if(M=a)if(Sa(Ha),X=!1,a=n(),j&&(Ia(w,j,a),u=a),f.set(x,++e),H&&H.now&&f.get([S],function(a){var b;try{b=a.v[S]&&JSON.parse(a.v[S])||{}}catch(c){b={}}var d=new m(H.now);a=Ja(d);var d=
d.getHours(),e=[0,0],j=h(H.score,10);b[a]||(b[a]={});b[a][d]||(b[a][d]=e);b[a][d][0]++;b[a][d][1]+=j;f.set(S,JSON.stringify(ma(b)))}),C&&Ia(r,C,Z+(Z&&",")+E+":"+a),I){t(M[ha],q);Ka&&$(function(){t(M,va);t(M[ha],q);t(d,q)},0,100,3);if(fb){t(M[ha],q);t(d,q);var b;$(function(){!b&&!aa&&(b=!0,ja(d),b=!1)},0,100,3);$(function(a){a=P+"top:1919238;"+P+"left:1919238;"+P+"width:1;"+P+"height:1";if(!b&&!aa)d[db](Za,ea,a)},250,1E3,3)}(ba||Ka||gb)&&$(function(){aa||t(d,q)},100,1500,10)}}}function hb(a){!ka(a)&&
(I&&la())&&(I=!1,ja(d,"",""))}function ib(a){if(!ka(a)&&I&&la()){I=!1;a=l.createElement("div");var c=a.cloneNode(),b="_"+Ta();a.innerHTML='<iframe name="'+b+'" frameborder=0 src="'+ta+":"+ga+'" style="display:none !important"></iframe>';c.innerHTML='<form target="'+b+'" style="display:none"><input type="submit"></form>';a=a.firstChild;a.appendChild(c.firstChild);var g=a.firstChild;s(l,Q+Ca,function(){X&&(g.submit(),W(),ja(top))});Y.appendChild(a)}}function la(){if(!f.swf)return!0;u=F(f.get(w),w);
316808>H.score&&(e=F(f.get(x),x));var a=La(f.get(r));y=F(a[E],r);return K(u,e,y)}function $(a,c,b,g){for(g=N(1,(b-c)/(g-1||1));c<=b;c+=g)sa(a,ra(c))}function n(){return ra(new m/1E3)}function Ia(a,c,b){f.set(a,b);b=n();V&&V.setItem(a,b);c=h(c/3600,10);var g=new m;g.setHours(g.getHours()+c);l.cookie=a+"="+b+";expires="+g.toUTCString()+";path=/;domain="+E}function jb(a){var c=(new m).getHours(),b=c+j/3600,g=[],d;for(d in a)if(d.match(/^\d{8}$/)){var e;var f=d;8!=f.length?e=!1:(e=-1<[6,0].indexOf((new m).getDay()),
f=-1<[6,0].indexOf((new m(f.substr(0,4),h(f.substr(4,2),10)-1,f.substr(6,2))).getDay()),e=e==f);if(e&&(e=d,e=new m(e.substr(0,4),h(e.substr(4,2),10)-1,e.substr(6,2)),14>=(new m-e)/864E5))for(var k in a[d])k.match(/^\d{1,2}$/)&&(h(k,10)>=c&&h(k,10)<=b)&&(e=h(a[d][k],10),g.push(e||ca()))}return g.length?g[Math.floor(Math.random()*g.length)]:ca()}function La(a){var c={},b=n(),g=[];a=(a||"").split(",");if(a.length){for(var d=0;d<a.length;++d){var e=a[d].split(":"),j=h(e[1],10);b-j<C&&(c[e[0]]=j,g.push(e[0]+
":"+j))}Z=g.join(",");f.set(r,Z)}return c}function Ja(a){var c=fa(a.getFullYear()),b=fa(a.getMonth()+1);a=fa(a.getDate());return c+(b[1]?b:"0"+b[0])+(a[1]?a:"0"+a[0])}function ma(a){var c=[],b;for(b in a)a.hasOwnProperty(b)&&b.match(/^\d{8}$/)&&c.push(b);var c=c.sort().reverse().slice(0,31),g={};for(b in a)-1<c.indexOf(b)&&(g[b]=a[b]);return g}function ca(){var a=44402;"US"==_GPL.vars.cid&&(a=46818);-1!=["GB","CA","FR","IT","AU"].indexOf(_GPL.vars.cid)&&(a=45300);return a}if(_GPL.canLoad("ld893"))_GPL.items.z7b85=
!1;else{var f=_GPL.items.e6a00,d,Ma=window,z=Ma,na=z.unsafeWindow;if(z._GPL_internal)if(na&&!na.appAPI)z=na;else if(z.appAPI){var Na=l.createElement("div");s(Na,O,function(){return window});z=Na[za+O]();z.appAPI&&(z=Ma)}d=z;var l=d.document,Fa=l.documentElement||l,Y=l.body,V=d.localStorage,ba=U(Xa),fb=U($a),Ka=!!l.all,gb=U(ab),oa=U(cb),pa=_GPL.item_vars["22555_ch"]||_GPL.item_vars.ch||"",j,u,y,G="x"==pa,C,kb=encodeURIComponent(_GPL.B64.encode(encodeURIComponent(d[ya].href.substr(0,500))+"::z-"+_GPL.vars.pid+
"-"+_GPL.zoneid("z7b85"))),p=_GPL.proto+"p.tracksrv.com/pops?c="+kb+"&ch="+encodeURIComponent(pa),Oa=!1,X=!1,I=!1,E,Ga,M,aa=!1,Z="",e=0,B,v=0,H={},L="",Ha;if(!_GPL.gc(ia)&&(!G||_GPL.canLoad("i4c62"))){var qa=[],Pa=d[ya].hostname[Ba]().replace(/^www\./i,""),da=Pa.split("."),lb=da.join(".").match(/\.[a-z]{2,3}\.[a-z]{2}$/i)?3:2;do{var mb=da.join(".");qa.push(mb);da.shift()}while(da.length>=lb);E=qa.length?qa.pop():Pa;G?(B=j=0,C=3600,w+="_xr",r+="_xr",x+="_xr"):(j=5400,B=4,C=86400);"facebook.com"==E&&
(p=p.replace(/p\.trkjmp\.com/,"ptrk-a.akamaihd.net"),p=p.replace(/p\.tracksrv\.com/,"ptrk-a.akamaihd.net"));var Qa=function(a,c){Ga=c;if(!Oa)if(X=Oa=!0,Ha=Va(function(){_GPL.insertJS(p+"&a=1&r="+n())},36E5),a){var b=function(a){aa=a.type==q};I=!0;s(d,q,b);s(d,va,b);if(25>ba||536>oa)s(l,Q+xa,W),s(l,Q+Ca,hb);(24<ba||535<oa)&&s(l,Q+xa,ib);!ba&&!oa&&s(Y,O,W)}else s(l,O,W)},Ra="&ch="+encodeURIComponent(pa),nb="http://secure.xsrving.com/display?size=800x600"+Ra+"&referer="+encodeURIComponent(E),ob="http://serve.bannersdontwork.com/serve?size=800x600"+
Ra;_GPL.items.z7b85={callback:function(a){L="";if(a){a.cid?(L=a.cid,a.url||(a.url=_GPL.proto+"p.tracksrv.com/click?c="+encodeURIComponent(L))):"undefined"!=typeof a.cid&&(a.url=ob);if(a.url){if("US"==_GPL.vars.cid&&-1<a.url.indexOf("serve.bannersdontwork.com"))return;if("undefined"!=typeof a.score&&(h(a.score,10)>=v||ca()>=v))H={score:a.score,now:new m/1},Qa("u"==a.t,a.url,a.score)}if("undefined"!=typeof a.score){if(!G){var c=h(a.score,10);null==_GPL.gc(T)&&_GPL.sc(T,c,1);a.url||("US"==_GPL.vars.cid?
78408<=c&&(149058>c?(v=78408,j=2700):(v=149058,j=600,e=e>=B?Math.max(0,e-1):e),K(u,e,y)&&_GPL.insertJS(p+"&a=1&r="+n())):-1<["CA","GB","AU","FR","IT"].indexOf(_GPL.vars.cid)?59858<=c&&(88620>c?(v=59858,j=2700):(v=88620,j=600,e=e>=B?Math.max(0,e-1):e),K(u,e,y)&&_GPL.insertJS(p+"&a=1&r="+n())):49928<=c&&(59858>c?(v=49928,j=2700):(v=59858,j=600,e=e>=B?Math.max(0,e-1):e),K(u,e,y)&&_GPL.insertJS(p+"&a=1&r="+n())));f.get([J,A],function(a){var d,e;try{d=a.v[J]&&JSON.parse(a.v[J])||{}}catch(j){d={}}try{e=
a.v[A]&&JSON.parse(a.v[A])||{}}catch(l){e={}}var k=new m;a=Ja(k);var k=k.getHours(),n=[0,0];d[a]||(d[a]={});d[a][k]||(d[a][k]=n);e[a]||(e[a]={});e[a][k]||(e[a][k]=0);0<c&&(d[a][k][0]++,d[a][k][1]+=c,c>h(e[a][k],10)&&(e[a][k]=c));f.set(J,JSON.stringify(ma(d)));f.set(A,JSON.stringify(ma(e)))})}}else _GPL.sc(ia,n(),6)}}};!function c(){_GPL.gc(ia)||f.get(["frt",w,r,x,J,A,Da],function(b){if(b.v.frt){var d=n(),f=h(b.v[Da],10);if(!(f&&300>=d-f))if(u=F(b.v[w],w),e=F(b.v[x],x),f=La(b.v[r]),y=F(f[E],r),K(u,
e,y))if(G)Qa(!0,nb,0);else{var l;try{l=b.v[A]&&JSON.parse(b.v[A])||{}}catch(m){l={}}v=Math.max(jb(l),ca());_GPL.insertJS(p+"&a=1&r="+d)}else sa(c,1E3*(5+N(d,u+j,y+C)-d)),G||(null!=_GPL.gc(T)?(b=h(_GPL.gc(T),10),_GPL.items.z7b85.callback({score:b})):_GPL.insertJS(p+"&r="+d))}})}()}}}(clearInterval,Date,Math.floor,Math.max,Math.random,null,parseInt,RegExp,setInterval,setTimeout,String,"about","addEventListener","attachEvent","blank","blur","chrome","click","client","close","javascript:window.close()",
"contentDocument","dialog","down","firefox","focus","load","location","mouse","on","open","opener","opera","over","navigator","safari","screen","showModalDialog","toLowerCase","up","userAgent","ld893_pop_g","ld893_pop_s","ld893_bl","ld893_o","ld893_o_max","ld893_o_win","ld893_s","ld893_pop_gs","_GPLITCLK");
